local TroopTableData = 
{
	[100] = 
	{
		name = "Wall",		
		category = "DEFENCE",		
		startLine = "DEFENCE",
		radius    = 1,		
		level     = 999,		
		maxNumber = 5000,		
		maxMorale = 100,		
		capacity  = 0,		
		movement  = 0,		
		supplyConsume = 0,		
		weapons   = {},
		armors    = { 100 },		
		traits    = { 300 },		
		prerequisites = { points=400, money=0, constrs = { 999 }, tech=-1, resource=0 }
	},
	[200] = 
	{
		name = "Gate",		
		category = "GATE",		
		startLine = "DEFENCE",		
		radius    = 1,		
		level     = 999,		
		maxNumber = 2000,
		maxMorale = 100,		
		capacity  = 0,		
		movement  = 0,		
		supplyConsume = 0,		
		weapons   = {},
		armors    = { 101 },		
		traits    = {},		
		prerequisites = { points=400, money=0, constrs = { 999 }, tech=1, resource=0 }
	},
	[210] = 
	{
		name = "Tower",		
		category = "TOWER",		
		startLine = "DEFENCE",		
		radius    = 1,
		level     = 999,		
		maxNumber = 500,
		maxMorale = 100,		
		capacity  = 0,		
		movement  = 0,		
		supplyConsume = 0,		
		weapons   = { 400 },
		armors    = { 100 },		
		traits    = {},
		prerequisites = { points=400, money=0, constrs = { 999 }, tech=1, resource=0 }
	},
	
	[300] = 
	{
		name = "Battering Ram",		
		category = "SIEGE_WEAPON",		
		startLine = "FRONT",		
		radius    = 5,		
		level     = 5,		
		maxNumber = 1000,
		maxMorale = 100,		
		capacity  = 0,		
		movement  = 30,		
		supplyConsume = 40,		
		weapons   = { 401 },
		armors    = { 500 },		
		traits    = {},		
		prerequisites = { points=400, money=0, constrs = { 999 }, tech=-1, resource=0 },
	},
	
	
	[301] = 
	{
		name = "Trebuchet",		
		category = "SIEGE_WEAPON",		
		startLine = "BACK",		
		level     = 8,		
		maxNumber = 600,		
		maxMorale = 100,		
		capacity  = 0,		
		movement  = 0,		
		supplyConsume = 40,		
		weapons   = { 402 },
		armors    = { 501 },		
		traits    = {},		
		prerequisites = { points=400, money=0, constrs = { 999 }, tech=-1, resource=0 },
	},
	
	[500] =
	{
		name = "Guard F1",
		category = "FOOTSOLDIER",		
		level     = 3,		
		maxNumber = 100,		
		maxMorale = 80,		
		capacity  = 0,		
		movement  = 20,		
		supplyConsume = 30,		
		weapons   = { 101 },
		armors    = { 300 },
		traits    = {},
		prerequisites = { points=100, constrs = { 999 } },
	},
	[501] =
	{
		name = "Guard F2",
		category = "FOOTSOLDIER",		
		level     = 3,		
		maxNumber = 200,		
		maxMorale = 80,		
		capacity  = 0,		
		movement  = 20,		
		supplyConsume = 30,		
		weapons   = { 101 },
		armors    = { 300 },
		traits    = {},
		prerequisites = { points=100, constrs = { 999 } },
	},
	[502] =
	{
		name = "Guard F3",
		category = "FOOTSOLDIER",		
		level     = 3,
		maxNumber = 500,		
		maxMorale = 80,		
		capacity  = 0,		
		movement  = 20,		
		supplyConsume = 30,		
		weapons   = { 101 },
		armors    = { 300 },
		traits    = {},
		prerequisites = { points=100, constrs = { 999 } },
	},
	[510] =
	{
		name = "Guard A1",
		category = "ARTILLERY",		
		level     = 3,
		maxNumber = 100,
		maxMorale = 80,
		capacity  = 0,
		movement  = 20,
		supplyConsume = 30,
		weapons   = { 100, 304 },
		armors    = { 300 },
		traits    = {},
		prerequisites = { points=100, constrs = { 999 } },
	},
	[511] =
	{
		name = "Guard A2",
		category = "ARTILLERY",		
		level     = 3,
		maxNumber = 200,		
		maxMorale = 80,		
		capacity  = 0,		
		movement  = 20,		
		supplyConsume = 30,		
		weapons   = { 100, 304 },
		armors    = { 300 },
		traits    = {},
		prerequisites = { points=100, constrs = { 999 } },
	},	
	[512] =
	{
		name = "Guard A3",
		category = "ARTILLERY",
		level     = 3,
		maxNumber = 500,		
		maxMorale = 80,		
		capacity  = 0,		
		movement  = 20,		
		supplyConsume = 30,		
		weapons   = { 100, 304 },
		armors    = { 300 },
		traits    = {},
		prerequisites = { points=100, constrs = { 999 } },
	},	
	
	[1000] = 
	{
		name = "Military",
		category = "FOOTSOLDIER",
		level     = 8,		
		maxNumber = 1000,		
		maxMorale = 100,		
		capacity  = 10,		
		movement  = 35,		
		supplyConsume = 100,
		weapons   = { 101, 305 },
		armors    = { 200, 300 },		
		traits    = { 301 },		
		prerequisites = { points=400, money=0, resource=0 },
	},
	[1001] = 
	{
		name = "Recruit Footman",
		category = "FOOTSOLDIER",		
		level     = 8,		
		maxNumber = 1000,		
		maxMorale = 100,		
		capacity  = 10,		
		movement  = 35,		
		supplyConsume = 100,		
		weapons   = { 100, 200, 305 },
		armors    = { 102, 200 },		
		traits    = { 301 },		
		prerequisites = { points=800, money=0, resource=0 },
	},
	[1002] = 
	{
		name = "Regular Footman",
		category = "FOOTSOLDIER",		
		level     = 8,		
		maxNumber = 1000,		
		maxMorale = 100,		
		capacity  = 10,		
		movement  = 35,		
		supplyConsume = 100,		
		weapons   = { 102, 200, 305 },
		armors    = { 201, 301, 400 },
		traits    = { 302 },		
		prerequisites = { points=800, money=0, constrs={999}, resource=0 },
	},
	[1002] = 
	{
		name = "Elite Footman",
		category = "FOOTSOLDIER",		
		level     = 8,		
		maxNumber = 1000,		
		maxMorale = 100,		
		capacity  = 10,		
		movement  = 35,		
		supplyConsume = 100,		
		weapons   = { 102, 201, 300 },
		armors    = { 201, 302, 401 },		
		traits    = { 310 },		
		prerequisites = { points=800, money=0, constrs={999}, resource=0 },
	},
	[2000] = 
	{
		name = "Recruit Archer",		
		category = "ARTILLERY",		
		startLine = "BACK",		
		level     = 8,		
		maxNumber = 1000,
		maxMorale = 90,		
		capacity  = 20,		
		movement  = 40,		
		supplyConsume = 80,		
		weapons   = { 100, 301 },
		armors    = { 200, 300 },		
		traits    = {},		
		prerequisites = { points=400, money=0, resource=0 },
	},
	[2001] = 
	{
		name = "Regular Archer",		
		category = "ARTILLERY",		
		startLine = "BACK",		
		level     = 8,		
		maxNumber = 1000,
		maxMorale = 90,		
		capacity  = 20,		
		movement  = 40,		
		supplyConsume = 80,		
		weapons   = { 100, 302 },
		armors    = { 200, 301 },		
		traits    = {},		
		prerequisites = { points=400, money=0, constrs={999}, resource=0 },
	},
	[2002] = 
	{
		name = "Elite Archer",		
		category = "ARTILLERY",		
		startLine = "BACK",		
		level     = 8,		
		maxNumber = 1000,
		maxMorale = 90,		
		capacity  = 20,		
		movement  = 40,		
		supplyConsume = 80,		
		weapons   = { 102, 303 },
		armors    = { 201, 301 },		
		traits    = {},		
		prerequisites = { points=400, money=0, constrs={999},resource=0 },
	},

	[3000] = 
	{
		name = "Scout",		
		category = "CAVALRY",
		startLine = "CHARGE",		
		level     = 10,		
		maxNumber = 500,
		maxMorale =	110,		
		capacity  = 40,		
		movement  = 70,		
		consume = 200,		
		weapons   = { 102, 300 },
		armors    = { 200, 301 },		
		traits    = {},
		prerequisites = { points=400, money=0, resource=0 },
	},
	[3001] = 
	{
		name = "Light Cavalry",		
		category = "CAVALRY",		
		startLine = "CHARGE",		
		level     = 10,		
		maxNumber = 500,
		maxMorale =	110,		
		capacity  = 40,		
		movement  = 70,		
		consume = 200,		
		weapons   = { 202, 300 },
		armors    = { 201, 302 },		
		traits    = {},
		prerequisites = { points=400, money=0, constrs={999}, resource=0 },
	},
	[3002] = 
	{
		name = "Heavy Cavalry",		
		category = "CAVALRY",		
		startLine = "CHARGE",		
		level     = 10,		
		maxNumber = 500,
		maxMorale =	110,		
		capacity  = 40,		
		movement  = 70,		
		consume = 200,		
		weapons   = { 102, 202 },
		armors    = { 201, 302, 400 },		
		traits    = {},
		prerequisites = { points=400, money=0, constrs={999}, resource=0 },
	},
}

function Scenario_Demo_Troop_TableData()
	return TroopTableData
end